### ISSUE TITLE
报错：ReferenceError:gardenTask is not defined

### ISSUE THREAD

**Issue by ypq123456789** [asunajs/asign#1]
![1709402614642](https://github.com/asunajs/asign/assets/114487221/7b62b4a9-92d8-45ff-86d3-2743ce59d0f7)

**Comment by ypq123456789** [comment]
删除gardenTask后，第一个手机号正常执行任务，第二个报错：
02:49:26.388
通知
脚本环境初始化...
<system>
02:49:26.457
通知
已开始执行
<system>
02:49:26.497
信息
执行第 1 行
caiyun.js:876:17
02:49:26.499
信息
--------------
caiyun.js:20:22
02:49:26.500
信息
你好：139xxxx0362
caiyun.js:20:22
02:49:27.624
信息
当前积分2066
caiyun.js:20:22
02:49:27.625
信息
网盘今日已签到
caiyun.js:20:22
02:49:28.691
信息
微信签到成功
caiyun.js:20:22
02:49:29.743
信息
剩余微信抽奖次数49，跳过执行
caiyun.js:20:22
02:49:31.850
信息
------【每日】------
caiyun.js:20:22
02:49:34.061
信息
执行第 2 行
caiyun.js:876:17
02:49:34.063
信息
--------------
caiyun.js:20:22
02:49:34.064
信息
你好：158xxxx2934
caiyun.js:20:22
02:49:34.815
信息
当前积分305
caiyun.js:20:22
02:49:34.816
信息
网盘今日已签到
caiyun.js:20:22
02:49:35.879
信息
微信签到成功
caiyun.js:20:22
02:49:36.945
信息
剩余微信抽奖次数49，跳过执行
caiyun.js:20:22
02:49:39.052
信息
------【每日】------
caiyun.js:20:22
02:49:39.527
错误
上传文件异常 Cannot read properties of undefined (reading 'phone')
caiyun.js:20:22
02:49:39.528
错误
TypeError:Cannot read properties of undefined (reading 'auth')
at dailyTask (caiyun.js:745:166)
at run (caiyun.js:820:9)
at main (caiyun.js:866:12)
at caiyun.js:877:9
